# Generated by Django 4.0.2 on 2022-03-31 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('user_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact like',
                'verbose_name_plural': 'Contact like',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='userslikes',
            constraint=models.UniqueConstraint(fields=('user', 'user_like'), name='unique_follow'),
        ),
    ]
